# example values
server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://komarreks:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate: 12
      dialect: org.hibernate.dialect.MySQL8Dialect
      generate_statistics: true
      order_inserts: true
      jdbc.batch_size: 100
    hibernate:
      ddl-auto: update
      show-sql: true

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
